"
"    .___________.   ____    ____     __     .___  ___. 
"    |           |   \   \  /   /    |  |    |   \/   | 
"    `---|  |----`    \   \/   /     |  |    |  \  /  | 
"        |  |          \      /      |  |    |  |\/|  | 
"        |  |           \    /       |  |    |  |  |  | 
"        |__|            \__/        |__|    |__|  |__| 
"    
" tvim, a vim config pack made by tjx 2015

" function! Timestamp()
"     let xdate = strftime("%Y-%m-%d")
"     exec ifdf
" endfunction
" nmap <leader>dt :Timestamp <esc>

nmap <c-l> <esc>:noh<cr>
nmap <leader>a :set filetype=awk        <CR>
nmap <leader>m :set filetype=markdown   <CR>
nmap <leader>t :set filetype=txt        <CR>
nmap <leader>e :set filetype=sed        <CR>
nmap <leader>h :set filetype=html       <CR>
nmap <leader>c :set filetype=css        <CR>
nmap <leader>j :set filetype=javascript <CR>
nmap <leader>p :set filetype=php        <CR>
nmap <leader>v :set filetype=vim        <CR>
nmap <leader>s :set filetype=sh         <CR>
set laststatus=2                            " status_bar
set statusline=T$\ %<%f
set statusline+=\ %{getcwd()}
set statusline+=%w%h%m%r                 
set statusline+=\ [%{&ff}:%{&fenc}:%Y]
set statusline+=%=%-14.(%l,%c%V%)\ %p%%
set printoptions=formfeed:y,header:0,paper:A4,duplex:off,syntax:n
set t_Co=256                                " 兼容putty下的vim
set textwidth=0                             " 关闭自动换行
set vb t_vb=                                " vim彻底关闭报错声
autocmd! bufwritepost _vimrc source %       " 通过vim编辑_vimrc文件并保存时,自动载入_vimrc
filetype on
filetype plugin on
filetype plugin indent on                   " required!
set ambiwidth=double
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936       " 这样打开不同编码的文件基本就不会出现乱码的情况。
set helplang=cn                             " 中文帮助文档
set autowriteall
set autoread                                " 设置当文件被改动时自动载入
set scrolloff=2                             " 光标移动到buffer的顶部和底部时保持3行距离
set clipboard+=unnamed                      " 共享剪贴板
set showcmd                                 " 输入的命令显示出来，看的清楚些
set ignorecase smartcase                    " 搜索时忽略大小写，除非在有一个或以上大写字母时
set cursorline                              " 高亮显示当前行
colorscheme torte " 样式设置
set tabstop=4     " tab宽度为4个字符
set shiftwidth=4  " tab的宽度
set expandtab     " 编辑时将所有tab替换为空格
set hidden        " 允许在有未保存的修改时切换缓冲区
set number        " 设置显示行号
set smarttab      " Be smart when using tabs
set autoindent    " 开启自动缩进
set smartindent   " 开启新行时使用智能自动缩进
set cindent       " 开启新行时使用智能自动缩进
let &mouse=""
set nocompatible               " be iMproved
set shell=/bin/bash
set nowrapscan
set pastetoggle=<F5>
au BufWinEnter *.sls set filetype=yaml
au BufWinEnter *.volt set filetype=html
au BufWinEnter *.mako set filetype=html
au BufWinEnter *.tp set filetype=html
au BufWinEnter *.md set filetype=markdown
" autocmd BufWinLeave *.* mkview
" autocmd BufWinEnter *.* silent loadview 

" Keep undo history across sessions by storing it in a file
if !exists('~/.vim/tmp')
    call system('mkdir -p ~/.vim/tmp/undodir ~/.vim/tmp/backupdir ~/.vim/tmp/directory')
endif
if has('persistent_undo')
    set undodir=$HOME/.vim/tmp/undodir
    set undofile " let g:persistentBehaviour=1
endif
if (has("win32") || has("win95") || has("win64") || has("win16"))
    let $VIMFILES = $VIM.'/vimfiles'
    autocmd GUIEnter * simalt ~x
    set encoding=cp936
    set backupdir=$TEMP
    set directory=$TEMP
    set printoptions=formfeed:y,header:0,paper:A4,duplex:off,syntax:n
else
    let $VIMFILES=$HOME.'/.vim'
    autocmd GUIEnter * silent !wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
    set encoding=utf-8
    set backupdir=~/.vim/tmp/backupdir
    set directory=~/.vim/tmp/directory
    set viewdir=~/.vim/tmp/view
endif

if has("gui")
    nmap <silent> <F2> : if &guioptions =~# 'T' <Bar>
    nmap <leader>2 : if &guioptions =~# 'T' <Bar>
    \set guioptions-=T <Bar> set guioptions-=m <Bar> else <Bar>
    \set guioptions+=T <Bar> set guioptions+=m <Bar> endif<CR>
    set guifont="Droid Sans Mono 11"            
    set guioptions-=m                           " Hide menu
    set guioptions-=T                           " Hide toolbar
    set guioptions-=L                           " Hide left scroll
    set guioptions+=b                           " Hide right scroll
endif

set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=$SSHHOME/.sshrc.d/vim/bundle/Vundle.vim
filetype off
call vundle#begin()

Plugin 'syntastic'
Plugin 'vim-gitgutter'
let g:gitgutter_max_signs=10000
Plugin 'scrooloose/nerdtree'
let NERDTreeShowHidden      = 0
let NERDTreeBookmarksFile   = $HOME.'/.vim/tmp/NerdBookmarks.txt'
let NERDTreeShowBookmarks   = 1
let NERDTreeShowFiles       = 1
let NERDTreeShowLineNumbers = 0
let NERDTreeWinPos          = 'left'
let NERDTreeWinSize         = 20
let NERDTreeMinimalUI       = 1
let NERDTreeIgnore          = ['.*\.chm', '.*\.ttf','.*\.lnk','.*\.cproj','.*\.exe','.*\.dll','.*\.out','.*\.files','.*\.png','.*\.jpg','.*\.jpeg','.*\.bmp','.*\.zip','.*\.rar','.*\.gif']
nmap <leader>3  : NERDTreeFind<cr>
Plugin 'tpope/vim-commentary'
" Plugin 'git@git.oschina.net:mrytsr/vim-phpmanual.git'

call vundle#end()            " required
filetype plugin indent on    " required

" Plugin 'ctrlp.vim'
" set wildignore+=*\\.git\\*,*\\.hg\\*,*\\.svn\\*,*.tgz,*.zip,*.url
" let g:ctrlp_match_window       = 'bottom,order:btt,min:5,max:5,results:10'
" let g:ctrlp_cmd                = 'CtrlPMixed'
" let g:ctrlp_mruf_default_order = 1
" Plugin 'tabular'
" Plugin 'timestamp.vim'
" let g:timestamp_regexp = '\v\C%(<%(Last %([cC]hanged?|modified)|Modified)\s*:\s+)@<=\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}|TIMESTAMP'
" let g:timestamp_rep='%Y-%m-%d %I:%M:%S'

" Plugin 'vim-startify'
" let g:startify_files_number = 20
" let g:startify_custom_header = [
"             \ '+------------------------------+',
"             \ '|  Welcome to my blog.         |',
"             \ '|                              |',
"             \ '|  http://hackers-delight.com/ |',
"             \ '+----------------+-------------+',
"             \]
" let g:startify_custom_footer = [
"             \ '+------------------------------+',
"             \ '|  1.01 ^ 365 =  37.78         |',
"             \ '+----------------+-------------+',
"             \]

" Plugin 'xptemplate'
" Plugin 'DoxygenToolkit'
" let g:DoxygenToolkit_versionString     = "0.1"
" let g:DoxygenToolkit_authorName        = "TangJX, mrytsr@gmail.com"
" let s:licenseTag                       = "Copyright(C)\<enter>"
" let g:DoxygenToolkit_licenseTag        = s:licenseTag
" let g:DoxygenToolkit_briefTag_funcName = "yes"
" let g:doxygen_enhanced_color           = 1
" nmap <leader>dx :Dox<CR>
" nmap <leader>da :DoxAut<CR>
" nmap <leader>dl :DoxLic<CR>
" Plugin 'pydiction-master'
" let g:pydiction_location = '/home/tjx/.vim/bundle/pydiction-master/complete-dict'
" Plugin 'vimcdoc-1.9.0'
" Plugin 'vim-ansible-yaml'
" Plugin 'ag'
" Plugin 'ack.vim'
" Plugin 'Align'
" Plugin 'SQLUtilities'
" Plugin 'surround.vim'
" Plugin cmdline-complete
" Plugin Conque-Shell-master
" Plugin dbext
" Plugin DBGPavim
" Plugin debugger
" Plugin emmet-vim
" Plugin grep
" Plugin indentLine
" Plugin JavaScript-syntax
" Plugin jedi-vim
" Plugin jQuery
" Plugin largefile
" Plugin matchit
" Plugin phpdoc-one
" Plugin pythoncomplete
" Plugin ShowMarks
" Plugin ske
" Plugin splitjoin
" Plugin tagbar-master
" Plugin vdebug
" Plugin vim-easymotion
" Plugin vim-javascript
" Plugin vimproc.vim-master
" Plugin vimshell.vim
" Plugin vim-yaml
